version: '3'
services:
  storage-api:
    image: ghcr.io/deadwood-ai/storage-api:v0.2.0
    restart: always
    ports:
      - 127.0.0.1:8000:8000
    environment:
      BASE_DIR: /data
    volumes:
      - ./data:/data