version: '3'
services:
  storage-api-stable:
    image: ghcr.io/deadwood-ai/storage-api:v0.4.0
    restart: always
    ports:
      - 127.0.0.1:40040:40040
    environment:
      BASE_DIR: /data
      UVICORN_PORT: 40040
      UVICORN_HOST: 0.0.0.0
      UVICORN_ROOT_PATH: /api/v1
      # There has to be a .env file that contains the following two lines
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_KEY: ${SUPABASE_KEY}
      METADATA_TABLE: upload_files
    volumes:
      - ./data:/data
  
  storage-api-dev:
    image: ghcr.io/deadwood-ai/storage-api:latest
    restart: always
    ports:
      - 127.0.0.1:40042:40042
    environment:
      BASE_DIR: /data
      UVICORN_PORT: 40042
      UVICORN_HOST: 0.0.0.0
      UVICORN_ROOT_PATH: /api/dev
      # There has to be a .env file that contains the following two lines
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_KEY: ${SUPABASE_KEY}
      METADATA_TABLE: upload_files_dev
    volumes:
      - ./dev-data:/data