services:
  deadwood-api:
    image: ghcr.io/deadwood-ai/deadwood-api:latest
    restart: always
    deploy:
      resources:
        limits:
          cpus: '4.5'
          memory: 5G
        reservations:
          cpus: '1'
          memory: 1G
    ports:
      - 127.0.0.1:40040:40040
    environment:
      # this is the location INSIDE the container, only change when the mountpoint changes
      BASE_DIR: /data

      # adjust the settings of the HOST folders here
      ARCHIVE_DIR: archive
      COG_DIR: cogs
      THUNMBNAIL_DIR: thumbnails

      # setup the uvicorn server here
      UVICORN_PORT: 40040
      UVICORN_HOST: 0.0.0.0
      UVICORN_ROOT_PATH: /api/v1

      # Supabase settings
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_KEY: ${SUPABASE_KEY}
      PROCESSOR_USERNAME: processor@deadtrees.earth
      PROCESSOR_PASSWORD: ${PROCESSOR_PASSWORD}

      # set the tables for the data
      DATASETS_TABLE: v1_datasets
      METADATA_TABLE: v1_metadata
      COGS_TABLE: v1_cogs
      LABELS_TABLE: v1_labels
      THUMBNAILS_TABLE: v1_thumbnails
      LOGS_TABLE: logs

      # queue settings
      QUEUE_TABLE: v1_queue
      QUEUE_POSITION_TABLE: v1_queue_positions
      CONCURRENT_TASKS: 2
      TASK_RETRY_DELAY: 60

    volumes:
      - ./production:/data

    command: python run.py server

  # add the mirgration server
  migrate:
    image: ghcr.io/deadwood-ai/deadwood-api:latest
    links:
      - deadwood-api
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
    environment:
      BASE_DIR: /data
      ARCHIVE_DIR: archive
      COG_DIR: cogs
      SUPABASE_KEY: ${SUPABASE_KEY}
      SUPABASE_URL: ${SUPABASE_URL}
      PROCESSOR_USERNAME: processor@deadtrees.earth
      PROCESSOR_PASSWORD: ${PROCESSOR_PASSWORD}
      OLD_ARCHIVE_PATH: /data/archive
      API_URL: http://deadwood-api:40040
      MIGRATION_TABLE: migrate_v1
      DATASETS_TABLE: v1_datasets
      METADATA_TABLE: v1_metadata
      COGS_TABLE: v1_cogs
      LABELS_TABLE: v1_labels
      QUEUE_TABLE: v1_queue
      QUEUE_POSITION_TABLE: v1_queue_positions
      CONCURRENT_TASKS: 2
      TASK_RETRY_DELAY: 60
    volumes:
      - ./production:/data
    command: echo "Use migration service like 'docker compose --rm migrate bash'"

