version: '3'
services:
  storage-api:
    image: ghcr.io/deadwood-ai/storage-api:v0.1.0
    restart: always
    ports:
      - 8000:8000
    environment:
      BASE_DIR: /data
    volumes:
      - ./data:/data